### PR TITLE
Native image IncludeAllLocales

### LINKED ISSUE #1238: MissingResourceRegistrationError `com/sun/tools/javac/resources/javac_en.properties` (native image 2.58.0)
## What happened?

pre-requisites:

1. I went to maven central https://repo1.maven.org/maven2/com/palantir/javaformat/palantir-java-format-native/2.58.0/
2. I downloaded `palantir-java-format-native-2.58.0-nativeImage-macos_aarch64.bin`
3. I did some setup:
```
chmod +x ~/Downloads/palantir-java-format-native-2.58.0-nativeImage-macos_aarch64.bin`
sudo xattr -rd com.apple.quarantine ~/Downloads/palantir-java-format-native-2.58.0-nativeImage-macos_aarch64.bin
alias pjf="~/Downloads/palantir-java-format-native-2.58.0-nativeImage-macos_aarch64.bin"
```
4. I found that simple sanity-checks worked: 
```
$ echo 'class Foo { /* hello*/ }' | pjf -                                                                     

class Foo {
  /* hello*/
}
```

problem: When I tried a more complicated hand-written file, I got a graal exception. Interestingly - this contained a TYPO making it invalid java... the `System.out.println` closing brace is wrong.

```
$ echo 'class Foo { /* hello*/ public void main(     String    aaaa ) {System.out.println("aaaaa"}; }}' | pjf - 

Exception in thread "main" com.oracle.svm.core.jdk.resources.MissingResourceRegistrationError: The program tried to access the resource at path

   com/sun/tools/javac/resources/javac_en.properties

without it being registered as reachable. Add it to the resource metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#resources-and-resource-bundles for help
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.resources.MissingResourceRegistrationUtils.missingResource(MissingResourceRegistrationUtils.java:44)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.Resources.createURLs(Resources.java:482)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.Resources.createURL(Resources.java:407)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.ResourcesHelper.nameToResourceURL(ResourcesHelper.java:107)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.ResourcesHelper.nameToResourceInputStream(ResourcesHelper.java:113)
	at java.base@23.0.1/jdk.internal.loader.BuiltinClassLoader.findResourceAsStream(BuiltinClassLoader.java:72)
	at java.base@23.0.1/java.lang.Module.getResourceAsStream(Module.java:1720)
	at java.base@23.0.1/java.util.ResourceBundle$ResourceBundleProviderHelper.lambda$loadPropertyResourceBundle$2(ResourceBundle.java:3691)
	at java.base@23.0.1/java.security.AccessController.executePrivileged(AccessController.java:132)
	at java.base@23.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.base@23.0.1/java.util.ResourceBundle$ResourceBundleProviderHelper.loadPropertyResourceBundle(ResourceBundle.java:3717)
	at java.base@23.0.1/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1846)
	at java.base@23.0.1/java.util.ResourceBundle.findBundle(ResourceBundle.java:1775)
	at java.base@23.0.1/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1663)
	at java.base@23.0.1/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:121)
	at java.base@23.0.1/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1548)
	at java.base@23.0.1/java.util.ResourceBundle.getBundle(ResourceBundle.java:931)
	at jdk.compiler@23.0.1/com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:123)
	at jdk.compiler@23.0.1/com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:142)
	at jdk.compiler@23.0.1/com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:168)
	at jdk.compiler@23.0.1/com.sun.tools.javac.util.AbstractDiagnosticFormatter.localize(AbstractDiagnosticFormatter.java:354)
	at jdk.compiler@23.0.1/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:112)
	at jdk.compiler@23.0.1/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
	at jdk.compiler@23.0.1/com.sun.tools.javac.util.JCDiagnostic.getMessage(JCDiagnostic.java:836)
	at com.palantir.javaformat.java.FormatterExceptions.toFormatterDiagnostic(FormatterExceptions.java:33)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:830)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
	at com.palantir.javaformat.java.FormatterException.<init>(FormatterException.java:36)
	at com.palantir.javaformat.java.FormatterExceptions.fromJavacDiagnostics(FormatterExceptions.java:28)
	at com.palantir.javaformat.java.Formatter.parseJcCompilationUnit(Formatter.java:194)
	at com.palantir.javaformat.java.Formatter.format(Formatter.java:127)
	at com.palantir.javaformat.java.Formatter.getFormatReplacements(Formatter.java:320)
	at com.palantir.javaformat.java.Formatter.formatSource(Formatter.java:297)
	at com.palantir.javaformat.java.FormatFileCallable.formatFile(FormatFileCallable.java:67)
	at com.palantir.javaformat.java.FormatFileCallable.call(FormatFileCallable.java:53)
	at com.palantir.javaformat.java.Main.formatStdin(Main.java:196)
	at com.palantir.javaformat.java.Main.format(Main.java:104)
	at com.palantir.javaformat.java.Main.main(Main.java:70)
	at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

### PR DESCRIPTION
**Pull request by crogoz**
## After this PR
Fixes: https://github.com/palantir/palantir-java-format/issues/1238

==COMMIT_MSG==
Native image IncludeAllLocales and updates reachability-metadata's resources glob to include all entries under `com/sun/tools/javac/resources/**`
==COMMIT_MSG==

### CODE REVIEW

File: palantir-java-format-jdk-bootstrap/src/test/java/com/palantir/javaformat/bootstrap/FormatterServicesTest.java [hunk 1]
```diff
@@ -78,6 +78,23 @@ void can_format_large_input_file(FormatterService formatterService) throws Forma
...
+                """
+            class Foo {
+
+            /* hello*/
+            public void main(     String    aaaa ) {
+                System.out.println("aaaaa"}; }
+            }
+        """;
+
+        assertThat(formatterService.getFormatReplacements(input, List.of(Range.open(0, input.length()))))
```
Comment (crogoz) [inline palantir-java-format-jdk-bootstrap/src/test/java/com/palantir/javaformat/bootstrap/FormatterServicesTest.java:94]: without this change, the issue is reproduced in the test

File: palantir-java-format-native/src/main/resources/META-INF/native-image/reachability-metadata.json [hunk 2]
```diff
@@ -164,26 +164,19 @@
...
-    },
-    {
-      "module": "jdk.compiler",
-      "glob": "com/sun/tools/javac/resources/compiler_en_US.properties"
+      "glob": "com/sun/tools/javac/resources/**"
     }
   ],
   "bundles": [
     {
-      "name": "com.sun.tools.javac.resources.compiler",
```
Comment (crogoz) [inline palantir-java-format-native/src/main/resources/META-INF/native-image/reachability-metadata.json:183]: we shouldn't restrict the locales for the compiler bundle - by default we will include everything

File: palantir-java-format-native/build.gradle [hunk 3]
```diff
@@ -69,12 +68,6 @@ graalvmNative {
     }
 }
 
-
-// The image requires parameters to be passed to; eg. gw nativeRun -Pargs=--palantir,-i,<file>
-tasks.named("nativeRun", org.graalvm.buildtools.gradle.tasks.NativeRunTask) {
```
Comment (crogoz) [inline palantir-java-format-native/build.gradle:74]: I don't think it makes sense to keep this here - I usually just run the native image directly

**Review by CRogers — APPROVED** [review]
