### PR TITLE
Fix: Properly format switch expressions

### LINKED ISSUE #1025: Poor formatting around expression switches
## What happened?

Pretty interesting, seems to only happen when the expression is assigned to a variable that was already declared.

```
    public void test1(int y) {
        int x =
                switch (y) {
                    case 1 -> 1;
                    case 2 -> throw new IllegalArgumentException();
                    default -> throw new IllegalStateException();
                };
    }

    public void test2(int y) {
        int x;
        x = switch (y) {
            case 1 -> 1;
            case 2 -> throw new IllegalArgumentException();
            default -> throw new IllegalStateException();};
    }
```

## What did you want to happen?

Probably this?

```
    public void test2(int y) {
        int x;
        x = switch (y) {
            case 1 -> 1;
            case 2 -> throw new IllegalArgumentException();
            default -> throw new IllegalStateException();
        };
    }
```

### PR DESCRIPTION
**Pull request by johnhany97**
## Before this PR
Fixes https://github.com/palantir/palantir-java-format/issues/1025 where before this change, we'd format switch expressions used in an assignment to yield the following:
```java
    public void test2(int y) {
        int x;
        x = switch (y) {
            case 1 -> 1;
            case 2 -> throw new IllegalArgumentException();
            default -> throw new IllegalStateException();};
    }
```

## After this PR

==COMMIT_MSG==
Properly format switch expressions
==COMMIT_MSG==
and now we generate this:
```java
    public void test2(int y) {
        int x;
        x = switch (y) {
            case 1 -> 1;
            case 2 -> throw new IllegalArgumentException();
            default -> throw new IllegalStateException();
        };
    }
```

### CODE REVIEW

File: gradle-palantir-java-format/src/test/groovy/com/palantir/javaformat/gradle/FormatDiffTest.java [hunk 1]
```diff
@@ -63,6 +63,7 @@ void reformat_a_subpath_of_a_git_directory_for_only_changed_lines() throws IOExc
         runCommandInRepo("git", "init");
         runCommandInRepo("git", "config", "user.name", "Test User");
         runCommandInRepo("git", "config", "user.email", "test-user@palantir.com");
+        runCommandInRepo("git", "config", "commit.gpgsign", "false");
```
Comment (johnhany97) [inline gradle-palantir-java-format/src/test/groovy/com/palantir/javaformat/gradle/FormatDiffTest.java:66]: Drive-by improvement: Didn't see it as necessary to sign the commits made by the test

File: palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/ExpressionSwitch.output [hunk 2]
```diff
@@ -47,4 +47,22 @@ class ExpressionSwitch {
...
         };
     }
+
+    public void test1(int y) {
+        int x =
+                switch (y) {
+                    case 1 -> 1;
+                    case 2 -> throw new IllegalArgumentException();
+                    default -> throw new IllegalStateException();
+                };
```
Comment (johnhany97) [inline palantir-java-format/src/test/resources/com/palantir/javaformat/java/testdata/ExpressionSwitch.output:57]: Would like to fix this in the future FWIW to instead be:
```java
        int x = switch (y) {
            case 1 -> 1;
            case 2 -> throw new IllegalArgumentException();
            default -> throw new IllegalStateException();
        };
```
But that requires more complicated changes to happen to the `visitAssignment` method which should be left to a separate PR

**Review by carterkozak — APPROVED** [review]
tyvm!
